[package]
name = "j2me_core"
version = "0.1.0"
edition = "2021"
authors = ["J2ME Emulator Team"]
description = "Núcleo de emulación J2ME en Rust (intérprete de bytecode JVM / CLDC y memoria segura)"

[lib]
name = "j2me_core"
crate-type = ["staticlib"]

[dependencies]
# Descompresión Deflate 100% Rust pura sin build scripts nativos de host
miniz_oxide = "0.9.1"
